import 'dotenv/config'
import { getPayload } from 'payload'
import config from '../payload.config.js'

function normalize(val: string): string {
  return val.toLowerCase().replace(/[^a-z0-9]/g, '').trim()
}

// Extract last comma-separated part if it looks like a city name (not a person name)
function extractCity(raw: string): string {
  const parts = raw.split(',').map(s => s.trim()).filter(Boolean)
  if (parts.length > 1) {
    // Use the last part if it's short (likely a city, not a person/founder name)
    const last = parts[parts.length - 1]
    if (last.length > 0 && last.length < 40 && !last.includes(' ')) {
      // Check it's not a person name by looking at the first part
      const first = parts[0]
      // If first part has a person name pattern like "Dr.", "Md.", "Shri", skip
      if (!/^(dr|md|shri|prof|mr|mrs|ms|smt)[.\s]/i.test(first)) {
        return last
      }
    }
  }
  return raw
}

async function main() {
  const payload = await getPayload({ config })
  payload.logger.info('Starting direct name-matching district mapping...')

  // Load all districts, indexed by normalized name
  const allDistricts = await payload.find({ collection: 'districts', limit: 2000, depth: 0 })
  const districtByName = new Map<string, { id: string; name: string }>()
  for (const d of allDistricts.docs as any[]) {
    const key = normalize(d.name)
    districtByName.set(key, { id: d.id, name: d.name })
  }
  payload.logger.info(`Loaded ${districtByName.size} districts`)

  // Also add state capitals / major cities to district mapping
  const CITY_TO_DISTRICT: Record<string, string> = {
    'mumbai': 'Mumbai City',
    'newdelhi': 'New Delhi',
    'delhi': 'New Delhi',
    'basaidarapur': 'New Delhi',
    'chennai': 'Chennai',
    'kolkata': 'Kolkata',
    'bengaluru': 'Bengaluru Urban',
    'bangalore': 'Bengaluru Urban',
    'hyderabad': 'Hyderabad',
    'ahmedabad': 'Ahmedabad',
    'pune': 'Pune',
    'jaipur': 'Jaipur',
    'lucknow': 'Lucknow',
    'kanpur': 'Kanpur Nagar',
    'nagpur': 'Nagpur',
    'indore': 'Indore',
    'bhopal': 'Bhopal',
    'surat': 'Surat',
    'vadodara': 'Vadodara',
    'patna': 'Patna',
    'ranchi': 'Ranchi',
    'chandigarh': 'Chandigarh',
    'dehradun': 'Dehradun',
    'shimla': 'Shimla',
    'panaji': 'North Goa',
    'gandhinagar': 'Gandhinagar',
    'bhubaneswar': 'Khordha',
    'raipur': 'Raipur',
    'guwahati': 'Kamrup Metropolitan',
    'imphal': 'Imphal West',
    'aizawl': 'Aizawl',
    'kohima': 'Kohima',
    'gangtok': 'Gangtok',
    'itanagar': 'Papum Pare',
    'agartala': 'West Tripura',
    'silvassa': 'Dadra and Nagar Haveli',
    'daman': 'Daman',
    'diu': 'Diu',
    'portblair': 'South Andaman',
    'kavaratti': 'Lakshadweep',
    'puducherry': 'Puducherry',
    'srinagar': 'Srinagar',
    'jammu': 'Jammu',
    'leh': 'Leh',
    'kargil': 'Kargil',
    'silchar': 'Cachar',
    'jorhat': 'Jorhat',
    'tezpur': 'Sonitpur',
    'dibrugarh': 'Dibrugarh',
    'coochbehar': 'Cooch Behar',
    'siliguri': 'Darjeeling',
    'haldwani': 'Nainital',
    'rishikesh': 'Dehradun',
    'mathura': 'Mathura',
    'ayodhya': 'Ayodhya',
    'varanasi': 'Varanasi',
    'agra': 'Agra',
    'allahabad': 'Prayagraj',
    'jhansi': 'Jhansi',
    'gorakhpur': 'Gorakhpur',
    'bareilly': 'Bareilly',
    'aligarh': 'Aligarh',
    'meerut': 'Meerut',
    'muzaffarnagar': 'Muzaffarnagar',
    'budaun': 'Budaun',
    'badaun': 'Budaun',
    'raebareli': 'Raebareli',
    'raibareli': 'Raebareli',
    'firozabad': 'Firozabad',
    'saharanpur': 'Saharanpur',
    'jhalawar': 'Jhalawar',
    'jamiamilliaislamianewdelhi': 'New Delhi',
    'chittorgarh': 'Chittorgarh',
    'bikaner': 'Bikaner',
    'ajmer': 'Ajmer',
    'udaipur': 'Udaipur',
    'jodhpur': 'Jodhpur',
    'kota': 'Kota',
    'alwar': 'Alwar',
    'bharatpur': 'Bharatpur',
    'sikar': 'Sikar',
    'bhilwara': 'Bhilwara',
    'pali': 'Pali',
    'tonk': 'Tonk',
    'nagaur': 'Nagaur',
    'churu': 'Churu',
    'jhunjhunu': 'Jhunjhunu',
    'jaisalmer': 'Jaisalmer',
    'barmer': 'Barmer',
    'sirohi': 'Sirohi',
    'sriganganagar': 'Sri Ganganagar',
    'dausa': 'Dausa',
    'dholpur': 'Dholpur',
    'karauli': 'Karauli',
    'sawaimadhopur': 'Sawai Madhopur',
    'banswara': 'Banswara',
    'dungarpur': 'Dungarpur',
    'baran': 'Baran',
    'bundi': 'Bundi',
    'hanumangarh': 'Hanumangarh',
    'pratapgarh': 'Pratapgarh',
    'rajsamand': 'Rajsamand',
    'sheopur': 'Sheopur',
    'shivpuri': 'Shivpuri',
    'ratlam': 'Ratlam',
    'mandsaur': 'Mandsaur',
    'satna': 'Satna',
    'shahdol': 'Shahdol',
    'chhindwara': 'Chhindwara',
    'narsinghpur': 'Narsinghpur',
    'seoni': 'Seoni',
    'vidisha': 'Vidisha',
    'siddipet': 'Siddipet',
    'nalgonda': 'Nalgonda',
    'warangal': 'Warangal',
    'vikarabad': 'Vikarabad',
    'karimnagar': 'Karimnagar',
    'nizamabad': 'Nizamabad',
    'adilabad': 'Adilabad',
    'nirmal': 'Nirmal',
    'suryapet': 'Suryapet',
    'machilipatnam': 'Krishna',
    'eluru': 'West Godavari',
    'nandyal': 'Kurnool',
    'kurnool': 'Kurnool',
    'nellore': 'Nellore',
    'vizianagaram': 'Vizianagaram',
    'srikakulam': 'Srikakulam',
    'tirupati': 'Tirupati',
    'anantapur': 'Anantapuramu',
    'kadapa': 'YSR',
    'guntur': 'Guntur',
    'kakinada': 'Kakinada',
    'mangalagiri': 'Guntur',
    'kanchipuram': 'Kancheepuram',
    'vellore': 'Vellore',
    'salem': 'Salem',
    'erode': 'Erode',
    'tiruppur': 'Tiruppur',
    'trichy': 'Tiruchirappalli',
    'madurai': 'Madurai',
    'thoothukudi': 'Thoothukudi',
    'tirunelveli': 'Tirunelveli',
    'nagercoil': 'Kanyakumari',
    'coimbatore': 'Coimbatore',
    'karur': 'Karur',
    'ranipet': 'Ranipet',
    'sivaganga': 'Sivaganga',
    'sivagangai': 'Sivaganga',
    'pudukkottai': 'Pudukkottai',
    'villupuram': 'Viluppuram',
    'dharmapuri': 'Dharmapuri',
    'krishnagiri': 'Krishnagiri',
    'namakkal': 'Namakkal',
    'perambalur': 'Perambalur',
    'ramanathapuram': 'Ramanathapuram',
    'theni': 'Theni',
    'tiruvarur': 'Tiruvarur',
    'tiruvannamalai': 'Tiruvannamalai',
    'ariyalur': 'Ariyalur',
    'tirupathur': 'Tirupathur',
    'kallakurichi': 'Kallakurichi',
    'mayiladuthurai': 'Mayiladuthurai',
    'tenkasi': 'Tenkasi',
    'chengalpattu': 'Chengalpattu',
    'shillong': 'East Khasi Hills',
    'shilong': 'East Khasi Hills',
    'goa': 'North Goa',
    'pondicherry': 'Puducherry',
    'purnea': 'Purnia',
    'purnia': 'Purnia',
    'bettiah': 'West Champaran',
    'madhepura': 'Madhepura',
    'deoghar': 'Deoghar',
    'keonjhar': 'Kendujhar',
    'balasore': 'Balasore',
    'tumkur': 'Tumakuru',
    'belagavi': 'Belagavi',
    'belgaum': 'Belagavi',
    'hubli': 'Dharwad',
    'dharwad': 'Dharwad',
    'haveri': 'Haveri',
    'karwar': 'Uttara Kannada',
    'kalaburagi': 'Kalaburagi',
    'gulbarga': 'Kalaburagi',
    'bijapur': 'Vijayapura',
    'vijayapura': 'Vijayapura',
    'bagalkot': 'Bagalkot',
    'ballari': 'Ballari',
    'bellary': 'Ballari',
    'chitradurga': 'Chitradurga',
    'chikkaballapura': 'Chikballapur',
    'chikkamagaluru': 'Chikkamagaluru',
    'kodagu': 'Kodagu',
    'koppal': 'Koppal',
    'mysore': 'Mysuru',
    'mandya': 'Mandya',
    'hassan': 'Hassan',
    'gadag': 'Gadag',
    'raichur': 'Raichur',
    'bidar': 'Bidar',
    'davanagere': 'Davanagere',
    'udupi': 'Udupi',
    'dakshinakannada': 'Dakshina Kannada',
    'mangalore': 'Dakshina Kannada',
    'manipal': 'Udupi',
    'yadgir': 'Yadgir',
    'yadgiri': 'Yadgir',
    'shivamogga': 'Shivamogga',
    'shimoga': 'Shivamogga',
    'ramanagara': 'Ramanagara',
    'chamarajanagar': 'Chamarajanagar',
    'yamunanagar': 'Yamunanagar',
    'faridabad': 'Faridabad',
    'gurugram': 'Gurugram',
    'rohtak': 'Rohtak',
    'hisar': 'Hisar',
    'ambala': 'Ambala',
    'karnal': 'Karnal',
    'panipat': 'Panipat',
    'sonipat': 'Sonipat',
    'rewari': 'Rewari',
    'jind': 'Jind',
    'kaithal': 'Kaithal',
    'bhiwani': 'Bhiwani',
    'mahendragarh': 'Mahendragarh',
    'fatehabad': 'Fatehabad',
    'sirsa': 'Sirsa',
    'palwal': 'Palwal',
    'mewat': 'Nuh',
    'nuh': 'Nuh',
    'panchkula': 'Panchkula',
    'charkhidadri': 'Charkhi Dadri',
    'diphu': 'Karbi Anglong',
    'nalbari': 'Nalbari',
    'nagaon': 'Nagaon',
    'dhubri': 'Dhubri',
    'tinsukia': 'Tinsukia',
    'kokrajhar': 'Kokrajhar',
    'jagdalpur': 'Bastar',
    'ambedkarnagar': 'Ambedkar Nagar',
    'basti': 'Basti',
    'siddharthnagar': 'Siddharthnagar',
    'mahrajganj': 'Maharajganj',
    'kushinagar': 'Kushinagar',
    'rampurhat': 'Birbhum',
    'raiganj': 'Uttar Dinajpur',
    'diamondharbour': 'South 24 Parganas',
    'tamralipto': 'Purba Medinipur',
    'jhargram': 'Jhargram',
    'kalyani': 'Nadia',
    'barasat': 'North 24 Parganas',
    'falkawn': 'Lunglei',
    'nahan': 'Sirmaur',
    'ambajogai': 'Beed',
    'bid': 'Beed',
    'baramati': 'Pune',
    'naroda': 'Ahmedabad',
    'visnagar': 'Mehsana',
    'himmatnagar': 'Sabarkantha',
    'siddhpur': 'Patan',
    'savli': 'Vadodara',
    'patan': 'Patan',
    'kalol': 'Gandhinagar',
    'vadnagar': 'Mehsana',
    'basna': 'Mehsana',
    'vahelal': 'Ahmedabad',
    'kuvadava': 'Rajkot',
    'dharpur': 'Patan',
    'limda': 'Vadodara',
    'mubarakpur': 'Gandhinagar',
    'sardarkrushinagar': 'Banaskantha',
    'ramayanpatti': 'Tirunelveli',
    'vepery': 'Chennai',
    'chomu': 'Jaipur',
    'begur': 'Bengaluru Urban',
    'indiranagar': 'Bengaluru Urban',
    'mohanpur': 'Nadia',
    'paithna': 'Sheikhpura',
    'bhaganbigha': 'Sheikhpura',
    'narsampet': 'Warangal',
    'rajannasircilla': 'Rajanna Sircilla',
    'sircilla': 'Rajanna Sircilla',
    'bhupalpally': 'Jayashankar Bhupalpally',
    'jayashankarbhupalpally': 'Jayashankar Bhupalpally',
    'jangaon': 'Jangaon',
    'kamareddy': 'Kamareddy',
    'amalapuram': 'East Godavari',
    'ongole': 'Prakasam',
    'chirala': 'Prakasam',
    'tenali': 'Guntur',
    'proddatur': 'YSR',
    'hindupur': 'Anantapuramu',
    'dharmavaram': 'Anantapuramu',
    'tadipatri': 'Anantapuramu',
    'chittoor': 'Chittoor',
    'madnur': 'Nizamabad',
    'miryalaguda': 'Nalgonda',
    'mahabubabad': 'Mahabubabad',
    'wanaparthy': 'Wanaparthy',
    'sangareddy': 'Sangareddy',
    'medchal': 'Medchal Malkajgiri',
    'shamshabad': 'Rangareddy',
    'gadwal': 'Jogulamba Gadwal',
    'jogulamba': 'Jogulamba Gadwal',
    'secunderabad': 'Hyderabad',
    'baghpat': 'Baghpat',
    'shamli': 'Shamli',
    'hapur': 'Hapur',
    'gautambuddhanagar': 'Gautam Buddha Nagar',
    'noida': 'Gautam Buddha Nagar',
    'ghaziabad': 'Ghaziabad',
    'bulandshahr': 'Bulandshahr',
    'etah': 'Etah',
    'kasganj': 'Kasganj',
    'farrukhabad': 'Farrukhabad',
    'kannauj': 'Kannauj',
    'etawah': 'Etawah',
    'auraiya': 'Auraiya',
    'kheri': 'Lakhimpur Kheri',
    'lakhimpurkheri': 'Kheri',
    'sitapur': 'Sitapur',
    'hardoi': 'Hardoi',
    'unnao': 'Unnao',
    'baraabanki': 'Barabanki',
    'barabanki': 'Barabanki',
    'faizabad': 'Ayodhya',
    'sultanpur': 'Sultanpur',
    'pratapgarhup': 'Pratapgarh',
    'jaunpur': 'Jaunpur',
    'azamgarh': 'Azamgarh',
    'mau': 'Mau',
    'ballia': 'Ballia',
    'deoria': 'Deoria',
    'santkabirnagar': 'Sant Kabir Nagar',
    'gonda': 'Gonda',
    'bahraich': 'Bahraich',
    'shravasti': 'Shravasti',
    'balrampur': 'Balrampur',
    'chitrakoot': 'Chitrakoot',
    'banda': 'Banda',
    'hamirpurup': 'Hamirpur',
    'mahoba': 'Mahoba',
    'lalitpur': 'Lalitpur',
    'jalandhar': 'Jalandhar',
    'amritsar': 'Amritsar',
    'ludhiana': 'Ludhiana',
    'patiala': 'Patiala',
    'bathinda': 'Bathinda',
    'mohali': 'Mohali',
    'pathankot': 'Pathankot',
    'hoshiarpur': 'Hoshiarpur',
    'kapurthala': 'Kapurthala',
    'firozpur': 'Firozpur',
    'fazilka': 'Fazilka',
    'gurdaspur': 'Gurdaspur',
    'mansa': 'Mansa',
    'moga': 'Moga',
    'sangrur': 'Sangrur',
    'barnala': 'Barnala',
    'faridkot': 'Faridkot',
    'muktsar': 'Muktsar',
    'tarnran': 'Tarn Taran',
    'tarn taran': 'Tarn Taran',
    'shahidbhagatsinghnagar': 'Shaheed Bhagat Singh Nagar',
    'rupnagar': 'Rupnagar',
    'cuttack': 'Cuttack',
    'puri': 'Puri',
    'sambalpur': 'Sambalpur',
    'rourekela': 'Sundargarh',
    'berhampur': 'Ganjam',
    'baripada': 'Mayurbhanj',
    'jharsuguda': 'Jharsuguda',
    'angul': 'Angul',
    'dhenkanal': 'Dhenkanal',
    'bhadrak': 'Bhadrak',
    'jajpur': 'Jajpur',
    'kendrapara': 'Kendrapara',
    'jagatsinghpur': 'Jagatsinghpur',
    'nayagarh': 'Nayagarh',
    'khordha': 'Khordha',
    'ganjam': 'Ganjam',
    'koraput': 'Koraput',
    'kandhamal': 'Kandhamal',
    'kalahandi': 'Kalahandi',
    'nuapada': 'Nuapada',
    'bargarh': 'Bargarh',
    'subarnapur': 'Subarnapur',
    'deogarh': 'Deogarh',
    'malkangiri': 'Malkangiri',
    'nabarangpur': 'Nabarangpur',
    'rayagada': 'Rayagada',
    'balangir': 'Balangir',
    'boudh': 'Boudh',
    'gajapati': 'Gajapati',
    'mumbaicity': 'Mumbai City',
    'mumbaisuburban': 'Mumbai Suburban',
    'andheri': 'Mumbai Suburban',
    'thane': 'Thane',
    'navimumbai': 'Thane',
    'nerul': 'Thane',
    'panvel': 'Raigad',
    'vashi': 'Thane',
    'alibag': 'Raigad',
    'lonikand': 'Ahmednagar',
    'karad': 'Satara',
    'miraj': 'Sangli',
    'wardha': 'Wardha',
    'akola': 'Akola',
    'amravati': 'Amravati',
    'aurangabad': 'Aurangabad',
    'nashik': 'Nashik',
    'dhule': 'Dhule',
    'jalgaon': 'Jalgaon',
    'kolhapur': 'Kolhapur',
    'solapur': 'Solapur',
    'latur': 'Latur',
    'nanded': 'Nanded',
    'parbhani': 'Parbhani',
    'hingoli': 'Hingoli',
    'osmanabad': 'Osmanabad',
    'beed': 'Beed',
    'jalna': 'Jalna',
    'chandrapur': 'Chandrapur',
    'gadchiroli': 'Gadchiroli',
    'gondia': 'Gondia',
    'bhandara': 'Bhandara',
    'ratnagiri': 'Ratnagiri',
    'sindhudurg': 'Sindhudurg',
    'sangli': 'Sangli',
    'satara': 'Satara',
    'nandurbar': 'Nandurbar',
    'yavatmal': 'Yavatmal',
    'washim': 'Washim',
    'palghar': 'Palghar',
    'raigad': 'Raigad',
    'pimprichinchwad': 'Pune',
    'mahasamund': 'Mahasamund',
    'durg': 'Durg',
    'bilaspurcg': 'Bilaspur',
    'raigarhcg': 'Raigarh',
    'korba': 'Korba',
    'raipurcg': 'Raipur',
    'ambikapur': 'Surguja',
    'surguja': 'Surguja',
    'jashpur': 'Jashpur',
    'bastar': 'Bastar',
    'dantewada': 'Dantewada',
    'bijapurcg': 'Bijapur',
    'narayanpur': 'Narayanpur',
    'kanker': 'Kanker',
    'kondagaon': 'Kondagaon',
    'sukma': 'Sukma',
    'balod': 'Balod',
    'balodabazar': 'Baloda Bazar',
    'balrampurcg': 'Balrampur',
    'bemetara': 'Bemetara',
    'dhamtari': 'Dhamtari',
    'gariaband': 'Gariaband',
    'gaurelapendramarwahi': 'Gaurela Pendra Marwahi',
    'janjgirchampa': 'Janjgir Champa',
    'kabirdham': 'Kabirdham',
    'koriya': 'Koriya',
    'mungeli': 'Mungeli',
    'rajnandgaon': 'Rajnandgaon',
    'surajpur': 'Surajpur',
  }

  // Get all unmapped colleges that have city
  const unmapped = await payload.find({
    collection: 'colleges',
    where: { and: [{ district: { exists: false } }, { city: { exists: true } }] },
    limit: 1000,
    depth: 0,
  })
  payload.logger.info(`Unmapped colleges with city: ${unmapped.docs.length}`)

  let mapped = 0
  let skipped = 0
  let errors = 0

  for (const c of unmapped.docs as any[]) {
    const city = c.city?.trim()
    if (!city) { skipped++; continue }

    // Try to extract actual city from compound names like "Jamia Millia Islamia, New Delhi"
    // Also try extracting just "New Delhi", "Imphal" etc from longer strings
    let extracted = extractCity(city)
    if (extracted === city) {
      // extractCity didn't help — try known suffix patterns
      const knownCities = ['New Delhi', 'Imphal', 'Delhi', 'Bangalore', 'Mumbai', 'Chennai', 'Kolkata', 'Hyderabad']
      for (const kc of knownCities) {
        if (city.toLowerCase().includes(kc.toLowerCase())) {
          extracted = kc
          break
        }
      }
    }
    const key = normalize(extracted)
    let districtName = CITY_TO_DISTRICT[key]
    
    if (!districtName) {
      // Try direct district name match
      const dMatch = districtByName.get(key)
      if (dMatch) {
        districtName = dMatch.name
      }
    }

    if (!districtName) {
      skipped++
      continue
    }

    // Look up district by name
    const districtEntry = districtByName.get(normalize(districtName))
    if (!districtEntry) {
      // Try to find it via payload query
      const found = await payload.find({
        collection: 'districts',
        where: { name: { equals: districtName } },
        limit: 1,
        depth: 0,
      })
      if (found.docs.length === 0) {
        skipped++
        continue
      }
      try {
        await payload.update({
          collection: 'colleges',
          id: c.id,
          data: { district: found.docs[0].id } as any,
          depth: 0,
        })
        mapped++
      } catch { errors++ }
      continue
    }

    try {
      await payload.update({
        collection: 'colleges',
        id: c.id,
        data: { district: districtEntry.id } as any,
        depth: 0,
      })
      mapped++
    } catch { errors++ }
  }

  payload.logger.info(`Mapped: ${mapped}, Skipped: ${skipped}, Errors: ${errors}`)
  process.exit(0)
}
main().catch((e) => { console.error(e); process.exit(1) })
