const categoryMap: Record<number, string> = {
  1: 'NEET Exam',
  2: 'NEET Exam',
  3: 'NEET Exam',
  4: 'NEET Exam',
  5: 'NEET Exam',
  6: 'NEET Exam',
  7: 'NEET Exam',
  8: 'NEET Exam',
  9: 'NEET Exam',
  10: 'NEET Exam',
  11: 'NEET Exam',
  12: 'Counselling Process',
  13: 'NEET Exam',
  14: 'NEET Exam',
  15: 'NBEMS/PG/SS',
  16: 'NBEMS/PG/SS',
  17: 'NBEMS/PG/SS',
  18: 'Counselling Process',
  19: 'State Counselling',
  20: 'Counselling Process',
  21: 'State Counselling',
  22: 'State Counselling',
  23: 'State Counselling',
  24: 'State Counselling',
  25: 'State Counselling',
  26: 'State Counselling',
  27: 'State Counselling',
  28: 'State Counselling',
  29: 'State Counselling',
  30: 'Counselling Process',
  31: 'Eligibility & Documents',
  32: 'Eligibility & Documents',
  33: 'Eligibility & Documents',
  34: 'NEET Exam',
  35: 'Fees & Finance',
  36: 'Fees & Finance',
  37: 'Fees & Finance',
  38: 'Counselling Process',
  39: 'Counselling Process',
  40: 'Counselling Process',
  41: 'Counselling Process',
  42: 'NBEMS/PG/SS',
  43: 'College-Specific',
  44: 'Eligibility & Documents',
  45: 'Eligibility & Documents',
  46: 'Counselling Process',
  47: 'Counselling Process',
  48: 'Counselling Process',
  49: 'Counselling Process',
  50: 'Counselling Process',
}

export function getCategory(blogNum: number): string {
  return categoryMap[blogNum] || 'General'
}
