const categoryMap: Record<number, string> = {
  1: 'NBEMS/PG/SS',
  2: 'State Counselling',
  3: 'State Counselling',
  4: 'NEET Exam',
  5: 'NBEMS/PG/SS',
  6: 'NBEMS/PG/SS',
  7: 'NBEMS/PG/SS',
  8: 'NBEMS/PG/SS',
  9: 'NBEMS/PG/SS',
  10: 'NBEMS/PG/SS',
  11: 'College-Specific',
  12: 'College-Specific',
  13: 'College-Specific',
  14: 'College-Specific',
  15: 'College-Specific',
  16: 'Fees & Finance',
  17: 'Fees & Finance',
  18: 'Fees & Finance',
  19: 'Eligibility & Documents',
  20: 'Eligibility & Documents',
  21: 'Eligibility & Documents',
  22: 'Eligibility & Documents',
  23: 'Eligibility & Documents',
  24: 'Eligibility & Documents',
  25: 'Counselling Process',
  26: 'College-Specific',
  27: 'College-Specific',
  28: 'College-Specific',
  29: 'College-Specific',
  30: 'State Counselling',
  31: 'State Counselling',
  32: 'Eligibility & Documents',
  33: 'Eligibility & Documents',
  34: 'NEET Exam',
  35: 'Counselling Process',
  36: 'Counselling Process',
  37: 'Counselling Process',
  38: 'Counselling Process',
  39: 'Counselling Process',
  40: 'State Counselling',
  41: 'State Counselling',
  42: 'State Counselling',
  43: 'State Counselling',
  44: 'State Counselling',
  45: 'State Counselling',
  46: 'State Counselling',
  47: 'State Counselling',
  48: 'State Counselling',
  49: 'NEET Exam',
  50: 'NEET Exam',
}

export function getCategory(blogNum: number): string {
  return categoryMap[blogNum] || 'General'
}
