/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    blogs: Blog;
    'pricing-cards': PricingCard;
    videos: Video;
    counselors: Counselor;
    helpdesk: Helpdesk;
    'live-counselling': LiveCounselling;
    pages: Page;
    subscriptions: Subscription;
    transactions: Transaction;
    'contact-submissions': ContactSubmission;
    specializations: Specialization;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    'pricing-cards': PricingCardsSelect<false> | PricingCardsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    counselors: CounselorsSelect<false> | CounselorsSelect<true>;
    helpdesk: HelpdeskSelect<false> | HelpdeskSelect<true>;
    'live-counselling': LiveCounsellingSelect<false> | LiveCounsellingSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    specializations: SpecializationsSelect<false> | SpecializationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'home-page-seo': HomePageSeo;
    'news-ticker': NewsTicker;
    'about-page': AboutPage;
    'video-categories': VideoCategory;
    testimonials: Testimonial;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page-seo': HomePageSeoSelect<false> | HomePageSeoSelect<true>;
    'news-ticker': NewsTickerSelect<false> | NewsTickerSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'video-categories': VideoCategoriesSelect<false> | VideoCategoriesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  phone?: string | null;
  role: 'admin' | 'editor' | 'user';
  avatar?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  /**
   * Select the focal point of the image for cropping
   */
  focalPoint?: {
    x?: number | null;
    y?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: string;
  title: string;
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blocks?:
    | (
        | {
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentBlock';
          }
        | {
            image: string | Media;
            caption?: string | null;
            alignment?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            title?: string | null;
            videoUrl: string;
            thumbnail?: (string | null) | Media;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoBlock';
          }
        | {
            quote: string;
            author?: string | null;
            style?: ('default' | 'highlight' | 'border') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            heading: string;
            description?: string | null;
            buttonText: string;
            buttonLink: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            type?: ('info' | 'warning' | 'success' | 'error') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'alertBlock';
          }
        | {
            title?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
      )[]
    | null;
  featuredImage?: (string | null) | Media;
  author?: (string | null) | User;
  categories?:
    | {
        category?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  status: 'draft' | 'published';
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (string | null) | Media;
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-cards".
 */
export interface PricingCard {
  id: string;
  /**
   * Internal name (e.g., "JOSAA Plan")
   */
  planName: string;
  /**
   * Card heading (e.g., "Complete JOSAA & CSAB Counselling Plan")
   */
  subtitle?: string | null;
  /**
   * Display price (e.g., "₹2399")
   */
  price: string;
  /**
   * Numeric price in paise for Razorpay (e.g., 239900 for ₹2399). 100 paise = ₹1.
   */
  priceInPaise: number;
  /**
   * Number of AI college predictions a user gets with this plan
   */
  predictionCredits: number;
  /**
   * Strikethrough price (e.g., "₹2999"). Leave empty for no strikethrough.
   */
  originalPrice?: string | null;
  /**
   * Discount badge (e.g., "20% OFF"). Leave empty for no badge.
   */
  discount?: string | null;
  /**
   * Badge text (e.g., "Premium", "NEW"). Shows if no discount.
   */
  badge?: string | null;
  /**
   * Card color scheme — all use brown family shades
   */
  colorScheme?: ('popular' | 'premium' | 'standard' | 'basic') | null;
  /**
   * College list (e.g., "DTU · NSUT · IIIT-D · IGDTUW · DSEU")
   */
  colleges?: string | null;
  description?: string | null;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Mark as most popular plan
   */
  popular?: boolean | null;
  ctaText?: string | null;
  ctaLink?: string | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: string;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * YouTube or Vimeo URL
   */
  videoUrl: string;
  thumbnail?: (string | null) | Media;
  /**
   * e.g. 12:34
   */
  duration?: string | null;
  category?: ('lecture' | 'tips' | 'interview' | 'other') | null;
  publishedAt?: string | null;
  status: 'draft' | 'published';
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (string | null) | Media;
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counselors".
 */
export interface Counselor {
  id: string;
  name: string;
  slug: string;
  designation: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  specializations?:
    | {
        specialization?: (string | null) | Specialization;
        id?: string | null;
      }[]
    | null;
  /**
   * Years of experience
   */
  experience?: number | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specializations".
 */
export interface Specialization {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "helpdesk".
 */
export interface Helpdesk {
  id: string;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('admission' | 'exam' | 'counselling' | 'pricing' | 'technical' | 'other') | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-counselling".
 */
export interface LiveCounselling {
  id: string;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  scheduledAt: string;
  counsellor?: (string | null) | Counselor;
  meetingUrl?: string | null;
  /**
   * e.g. 1 hour, 30 minutes
   */
  duration?: string | null;
  status: 'scheduled' | 'live' | 'completed' | 'cancelled';
  maxParticipants?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  content?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            backgroundImage?: (string | null) | Media;
            ctaText?: string | null;
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentBlock';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            heading?: string | null;
            testimonials?:
              | {
                  name: string;
                  quote: string;
                  image?: (string | null) | Media;
                  designation?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading: string;
            description?: string | null;
            buttonText: string;
            buttonLink: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  status: 'draft' | 'published';
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (string | null) | Media;
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Tracks user plan purchases and admin assignments
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: string;
  /**
   * The user who purchased this plan
   */
  user: string | User;
  /**
   * Which plan was purchased
   */
  plan: string | PricingCard;
  /**
   * The payment transaction for this subscription
   */
  transaction?: (string | null) | Transaction;
  /**
   * Set to "active" once both counselor and page are assigned
   */
  status: 'pending' | 'active' | 'cancelled' | 'expired';
  /**
   * Counselor assigned to this user (set by admin)
   */
  assignedCounselor?: (string | null) | Counselor;
  /**
   * CMS page the user will see on /my-plan (set by admin)
   */
  assignedPage?: (string | null) | Page;
  /**
   * Auto-set on creation
   */
  purchasedAt?: string | null;
  /**
   * Auto-set when status becomes active
   */
  assignedAt?: string | null;
  /**
   * Total credits granted with this plan (auto-set from plan on creation)
   */
  creditsTotal?: number | null;
  /**
   * Remaining prediction credits (decremented on each use)
   */
  creditsRemaining?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks Razorpay payment transactions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  user: string | User;
  plan: string | PricingCard;
  /**
   * Subscription created after successful payment
   */
  subscription?: (string | null) | Subscription;
  /**
   * Razorpay order ID
   */
  razorpayOrderId?: string | null;
  /**
   * Razorpay payment ID (set after successful payment)
   */
  razorpayPaymentId?: string | null;
  /**
   * Razorpay payment signature (for verification)
   */
  razorpaySignature?: string | null;
  /**
   * Amount in paise (e.g., 239900 for ₹2399)
   */
  amount: number;
  currency: string;
  status: 'created' | 'attempted' | 'paid' | 'failed' | 'refunded';
  /**
   * Prevents duplicate order creation
   */
  idempotencyKey?: string | null;
  /**
   * e.g., upi, card, netbanking
   */
  paymentMethod?: string | null;
  paidAt?: string | null;
  /**
   * Error details if payment failed
   */
  errorMessage?: string | null;
  /**
   * Audit log of received webhook events
   */
  webhookEvents?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  subject?: string | null;
  message: string;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'blogs';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'pricing-cards';
        value: string | PricingCard;
      } | null)
    | ({
        relationTo: 'videos';
        value: string | Video;
      } | null)
    | ({
        relationTo: 'counselors';
        value: string | Counselor;
      } | null)
    | ({
        relationTo: 'helpdesk';
        value: string | Helpdesk;
      } | null)
    | ({
        relationTo: 'live-counselling';
        value: string | LiveCounselling;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: string | Subscription;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'specializations';
        value: string | Specialization;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  role?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  focalPoint?:
    | T
    | {
        x?: T;
        y?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  blocks?:
    | T
    | {
        contentBlock?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              image?: T;
              caption?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        videoBlock?:
          | T
          | {
              title?: T;
              videoUrl?: T;
              thumbnail?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              quote?: T;
              author?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              heading?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        alertBlock?:
          | T
          | {
              content?: T;
              type?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  featuredImage?: T;
  author?: T;
  categories?:
    | T
    | {
        category?: T;
        id?: T;
      };
  publishedAt?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-cards_select".
 */
export interface PricingCardsSelect<T extends boolean = true> {
  planName?: T;
  subtitle?: T;
  price?: T;
  priceInPaise?: T;
  predictionCredits?: T;
  originalPrice?: T;
  discount?: T;
  badge?: T;
  colorScheme?: T;
  colleges?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  popular?: T;
  ctaText?: T;
  ctaLink?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  videoUrl?: T;
  thumbnail?: T;
  duration?: T;
  category?: T;
  publishedAt?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counselors_select".
 */
export interface CounselorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  designation?: T;
  bio?: T;
  image?: T;
  specializations?:
    | T
    | {
        specialization?: T;
        id?: T;
      };
  experience?: T;
  email?: T;
  phone?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "helpdesk_select".
 */
export interface HelpdeskSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-counselling_select".
 */
export interface LiveCounsellingSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  scheduledAt?: T;
  counsellor?: T;
  meetingUrl?: T;
  duration?: T;
  status?: T;
  maxParticipants?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              ctaText?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        contentBlock?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              testimonials?:
                | T
                | {
                    name?: T;
                    quote?: T;
                    image?: T;
                    designation?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
      };
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  user?: T;
  plan?: T;
  transaction?: T;
  status?: T;
  assignedCounselor?: T;
  assignedPage?: T;
  purchasedAt?: T;
  assignedAt?: T;
  creditsTotal?: T;
  creditsRemaining?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  user?: T;
  plan?: T;
  subscription?: T;
  razorpayOrderId?: T;
  razorpayPaymentId?: T;
  razorpaySignature?: T;
  amount?: T;
  currency?: T;
  status?: T;
  idempotencyKey?: T;
  paymentMethod?: T;
  paidAt?: T;
  errorMessage?: T;
  webhookEvents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specializations_select".
 */
export interface SpecializationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Left-side logo (e.g., Ministry of Education emblem)
   */
  logo?: (string | null) | Media;
  /**
   * Right-side emblem/logo (e.g., NTA or organization logo)
   */
  emblem?: (string | null) | Media;
  tagline?: string | null;
  navigation?:
    | {
        label: string;
        link: string;
        /**
         * Controls when this nav item is visible based on authentication state
         */
        showWhen?: ('always' | 'authenticated' | 'unauthenticated') | null;
        children?:
          | {
              label: string;
              link: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaButton?: {
    text?: string | null;
    link?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logo?: (string | null) | Media;
  description?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  policyLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'twitter' | 'instagram' | 'youtube' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  creditsText?: string | null;
  businessHours?: string | null;
  supportEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName?: string | null;
  siteNameHindi?: string | null;
  siteDescription?: string | null;
  contactEmail?: string | null;
  /**
   * Phone number for call button (e.g., +91-9876543210)
   */
  phone?: string | null;
  /**
   * WhatsApp number
   */
  whatsapp?: string | null;
  address?: string | null;
  socialMedia?: {
    facebook?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    linkedin?: string | null;
  };
  /**
   * Trust badge statistics displayed on homepage
   */
  stats?: {
    students?: string | null;
    support?: string | null;
    personalized?: string | null;
    counselors?: string | null;
  };
  /**
   * Homepage hero section content
   */
  hero?: {
    badge?: string | null;
    heading?: string | null;
    priceText?: string | null;
    description?: string | null;
    hindiDescription?: string | null;
    primaryCtaText?: string | null;
    primaryCtaLink?: string | null;
    secondaryCtaText?: string | null;
    secondaryCtaLink?: string | null;
  };
  /**
   * Top government branding bar
   */
  topBar?: {
    leftText?: string | null;
    rightText?: string | null;
  };
  /**
   * Homepage notification banner displayed below the hero section
   */
  notificationBar?: {
    text?: string | null;
    link?: string | null;
    isEnabled?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page-seo".
 */
export interface HomePageSeo {
  id: string;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (string | null) | Media;
  keywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-ticker".
 */
export interface NewsTicker {
  id: string;
  items?:
    | {
        title: string;
        link?: string | null;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the /about page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  hero: {
    badge?: string | null;
    title: string;
    subtitle?: string | null;
  };
  mission: {
    heading: string;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Shown in the 2×2 stats grid next to the mission text. Use "Gold" accent for the primary number.
     */
    stats?:
      | {
          value: string;
          label: string;
          accent?: ('navy' | 'gold') | null;
          id?: string | null;
        }[]
      | null;
  };
  whyChooseUs: {
    heading: string;
    intro?: string | null;
    items?:
      | {
          title: string;
          description: string;
          icon: 'Award' | 'Target' | 'BookOpen' | 'Headphones' | 'Heart' | 'Users';
          id?: string | null;
        }[]
      | null;
  };
  team: {
    heading: string;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Shown below the team description. Use "Gold" accent for the primary number.
     */
    stats?:
      | {
          value: string;
          label: string;
          accent?: ('navy' | 'gold') | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Optional extra content blocks rendered after the Team section
   */
  extraSections?:
    | {
        heading?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (string | null) | Media;
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-categories".
 */
export interface VideoCategory {
  id: string;
  items?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  testimonials?:
    | {
        name: string;
        quote: string;
        image?: (string | null) | Media;
        designation?: string | null;
        rating: number;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  emblem?: T;
  tagline?: T;
  navigation?:
    | T
    | {
        label?: T;
        link?: T;
        showWhen?: T;
        children?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  ctaButton?:
    | T
    | {
        text?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  description?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  policyLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  creditsText?: T;
  businessHours?: T;
  supportEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteNameHindi?: T;
  siteDescription?: T;
  contactEmail?: T;
  phone?: T;
  whatsapp?: T;
  address?: T;
  socialMedia?:
    | T
    | {
        facebook?: T;
        twitter?: T;
        instagram?: T;
        youtube?: T;
        linkedin?: T;
      };
  stats?:
    | T
    | {
        students?: T;
        support?: T;
        personalized?: T;
        counselors?: T;
      };
  hero?:
    | T
    | {
        badge?: T;
        heading?: T;
        priceText?: T;
        description?: T;
        hindiDescription?: T;
        primaryCtaText?: T;
        primaryCtaLink?: T;
        secondaryCtaText?: T;
        secondaryCtaLink?: T;
      };
  topBar?:
    | T
    | {
        leftText?: T;
        rightText?: T;
      };
  notificationBar?:
    | T
    | {
        text?: T;
        link?: T;
        isEnabled?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page-seo_select".
 */
export interface HomePageSeoSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-ticker_select".
 */
export interface NewsTickerSelect<T extends boolean = true> {
  items?:
    | T
    | {
        title?: T;
        link?: T;
        isActive?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        subtitle?: T;
      };
  mission?:
    | T
    | {
        heading?: T;
        body?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              accent?: T;
              id?: T;
            };
      };
  whyChooseUs?:
    | T
    | {
        heading?: T;
        intro?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  team?:
    | T
    | {
        heading?: T;
        body?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              accent?: T;
              id?: T;
            };
      };
  extraSections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-categories_select".
 */
export interface VideoCategoriesSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  testimonials?:
    | T
    | {
        name?: T;
        quote?: T;
        image?: T;
        designation?: T;
        rating?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}